name = "stealth-forex-api"
main = "src/index.js"
compatibility_date = "2024-11-27"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "forex-rates"
database_id = "05ede330-5c35-4aee-8843-6c3527817925"
