name = "api"
main = "src/index.js"
compatibility_date = "2024-11-27"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "chhotkari"
database_id = "cf2d6236-f746-4ab1-b01e-791944638b5f"
